name: Auto CVE Push Service

on:
  schedule:
    - cron: '0 * * * *'   # '0 23 * * *' 每天 23 点执行（UTC 时间）（实测执行时间可能会因为GitHub Actions的队列延迟而延后，如果在东八区，相当于北京时间上午 7-8 点，一个小时左右属于正常的波动范围）
  workflow_dispatch:       # 手动触发

jobs:
  run-cveflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          pip install serverchan-sdk
          
      - name: Download previous DB
        uses: actions/download-artifact@v4
        with:
          name: vulns-db
          path: .  # 下载到工作目录
        continue-on-error: true  # 首次运行时忽略错误

      - name: Run CVE Push Service script
        env:
          SCKEY: ${{ secrets.SCKEY }}   # 从 GitHub Secrets 注入
        run: |
          python CVE_PushService.py

      - name: Check if new vulnerabilities were found
        id: check_vulns
        run: |
          if [ -f new_vulns.flag ]; then
            echo "new_vulns=true" >> $GITHUB_ENV
            echo "---- New Vulnerabilities Found ----"
            cat new_vulns.flag
            echo "-----------------------------------"
          else
            echo "new_vulns=false" >> $GITHUB_ENV
            echo "No new vulnerabilities."
          fi

      - name: Upload CVE Push Service log (only if new vulns found)
        if: env.new_vulns == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cveflows-log
          path: cveflows.log

      - name: Upload updated DB
        uses: actions/upload-artifact@v4
        with:
          name: vulns-db
          path: vulns.db  # 上传当前数据库
          retention-days: 7
